# Generated by Django 4.1 on 2024-05-15 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('cover', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='image_covers', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
    ]
